version: "3"
services:
  ui:
    build:
      context: ./Frontend
      dockerfile: ./docker/vue3/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./Frontend/ui:/app
    environment:
      VUE_APP_USERURL: http://localhost:8082/app/
      VUE_APP_ANALYSISURL: http://localhost:8081/
    command: npm run serve

  app:
    build:
      context: ./keywordapi/app
      dockerfile: ./docker/app/Dockerfile
    image: youtube_analysis_app
    ports:
      - "8081:8081"
    volumes:
    - ./keywordapi/app/src:/app/src
    tty: true
    environment:
      TZ: Asia/Tokyo
      PORT: 8081
      CORS_ADDRESS: http://localhost:8080
    env_file:
    - ./keywordapi/app/docker/test/.env
    # command: flask run --host 0.0.0.0 --port 8081

  go:
    build:
      context: ./loginapi/app
      dockerfile: Dockerfile
    image: loginapi
    container_name: loginapi
    environment:
      PORT: 8082
      CORS_ADDRESS: http://localhost:8080
    env_file:
    - ./loginapi/app/.env
    command: go run main.go
    # command: /bin/sh -c "go run main.go"
    # command: sh -c "reflex -s -r '\.go$$' "
    # command: >
    #   sh -c "reflex -s -r '\.go$$' go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ./loginapi/app:/go/src/app
    ports:
      - "8082:8082"