swagger: '2.0'
info:
  title: loginAPI
  description: login API on API Gateway with a Cloud Run backend
  version: 1.0.1
schemes:
- https
produces:
- application/json
x-google-backend:
  address: ${Backend_Address}

paths:
  /app/user:
    get:
      summary: get user infomation
      operationId: getuser
      responses:
        '200':
          description: A successful response
    options:
      summary: cors authentication
      operationId: authcorsuser
      responses:
        '204':
          description: A successful response


  /app/login:
    post:
      summary: login on web
      operationId: login
      parameters:
        - in: body
          name: login
          schema:
            $ref: '#/definitions/Login'
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      summary: cors authentication
      operationId: authcorslogin
      responses:
        '204':
          description: A successful response

  /app/logout:
    get:
      summary: logout on web
      operationId: logout
      # parameters:
      #   - in: body
      #     name: login
      #     schema:
      #       $ref: '#/definitions/Login'
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      summary: cors authentication
      operationId: authcorslogout
      responses:
        '204':
          description: A successful response

  /app/register:
    post:
      summary: register account on web
      operationId: register
      parameters:
        - in: body
          name: register
          schema:
            $ref: '#/definitions/Register'
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      summary: cors authentication
      operationId: authcorsregister
      responses:
        '204':
          description: A successful response


  /app/forgot:
    post:
      summary: send email for resetting password
      operationId: forgot
      parameters:
        - in: body
          name: forgot
          schema:
            $ref: '#/definitions/Forgot'
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      summary: cors authentication
      operationId: authcorsforgot
      responses:
        '204':
          description: A successful response

  /app/reset:
    post:
      summary: reset password
      operationId: reset
      parameters:
        - in: body
          name: reset
          schema:
            $ref: '#/definitions/Reset'
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      summary: cors authentication
      operationId: authcorsreset
      responses:
        '204':
          description: A successful response

  /app/contact:
    post:
      summary: contact owner
      operationId: contact
      parameters:
        - in: body
          name: contact
          schema:
            $ref: '#/definitions/Contact'
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      summary: cors authentication
      operationId: authcorscontact
      responses:
        '204':
          description: A successful response


definitions:
  Login:
    properties:
      email:
        type: string
      password:
        type: string
    # Both properties are required
    required:  
      - email
      - password

  Register:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      password:
        type: string
      password_connfirm:
        type: string
    required:  
      - first_name
      - last_name
      - email
      - password
      - password_confirm

  Forgot:
    properties:
      email:
        type: string
    required:  
      - email

  Reset:
    properties:
      token:
        type: string
      password:
        type: string
      password_confirm:
        type: string
    required:  
      - token
      - password
      - password_confirm

  Contact:
    properties:
      id:
        type: string
      title:
        type: string
      content:
        type: string
      email:
        type: string
    required:  
      - id
      - title
      - content
      - email