version: '3'
services:
  go:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: loginapi
    container_name: loginapi
    env_file:
    - ./app/.env
    environment:
      CORS_ADDRESS: http://localhost:8080
      # GIN_MODE: release
    command: go run main.go
    # command: >
    #   sh -c "reflex -s -r '\.go$$' go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ./app:/go/src/app
    ports:
      - "8080:8080"