version: '3'
services:
  go:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: loginapi
    container_name: loginapi
    environment:
      GCP_KEYFILE_JSON: ${GCP_KEYFILE_JSON}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      CORS_ADDRESS: ${CORS_ADDRESS}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_TEMPLATED_ID: ${SENDGRID_TEMPLATED_ID}
      SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}
      TESTUSER_FIRSTNAME: ${TESTUSER_FIRSTNAME}
      TESTUSER_LASTNAME: ${TESTUSER_LASTNAME}
      TESTUSER_EMAIL: ${TESTUSER_EMAIL}
      TESTUSER_PASSWORD: ${TESTUSER_PASSWORD}
      TESTUSER_PASSWORD_CONFIRM: ${TESTUSER_PASSWORD_CONFIRM}
      GIN_MODE: release
    command: go run main.go
    # command: >
    #   sh -c "reflex -s -r '\.go$$' go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ./app:/go/src/app
    ports:
      - "8080:8080"