version: '3'

services:
  apptest:
    build:
      context: ./app
      dockerfile: ./docker/test/Dockerfile
    image: youtube_analysis_apptest
    container_name: apptest
    ports:
      - "8080:8080"
      # - "8080:8080"
    volumes:
    - ./app/src:/app/src
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_DEBUG: 1
      GOOGLE_APPLICATION_CREDENTIALS: credentials/key.json
      GCP_API_KEY: ${GCP_API_KEY}
      GCP_KEYFILE_JSON: ${GCP_KEYFILE_JSON}
      GCP_STORAGE_BUCKET: ${GCP_STORAGE_BUCKET}
      GCP_TRANSLATE_FOLDER: ${GCP_TRANSLATE_FOLDER}
      GCP_COMPLEHEND_FOLDER: ${GCP_COMPLEHEND_FOLDER}
      GCP_ENTITIES_FOLDER: ${GCP_ENTITIES_FOLDER}
      GCP_ANALYSIS_FOLDER: ${GCP_ANALYSIS_FOLDER}
      CORS_ADDRESS: ${CORS_ADDRESS}
      TESTUSER_ID: ${TESTUSER_ID}
      TESTUSER_TRANSLATE_FILENAME: ${TESTUSER_TRANSLATE_FILENAME}
      TESTUSER_ANALYSIS_FILENAME: ${TESTUSER_ANALYSIS_FILENAME}
    # env_file:
    # - ./app/docker/test/.env
    command: flask run --host 0.0.0.0 --port 8000