version: '3'

services:
  apptest:
    build:
      context: ./app
      dockerfile: ./docker/test/Dockerfile
    image: youtube_analysis_apptest
    container_name: apptest
    ports:
      - "8080:8080"
    volumes:
    - ./app/src:/app/src
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_DEBUG: 1
      GCP_API_KEY: ${GCP_API_KEY}
      AWS_STORAGE_BUCKET: ${AWS_STORAGE_BUCKET}
      AWS_TRANSLATE_FOLDER: ${AWS_TRANSLATE_FOLDER}
      AWS_COMPLEHEND_FOLDER: ${AWS_COMPLEHEND_FOLDER}
      AWS_ENTITIES_FOLDER: ${AWS_ENTITIES_FOLDER}
      AWS_ANALYSIS_FOLDER: ${AWS_ANALYSIS_FOLDER}
      AWS_LAMBDA_LIST: ${AWS_LAMBDA_LIST}
      AWS_LAMBDA_DETAIL: ${AWS_LAMBDA_DETAIL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      CORS_ADDRESS: ${CORS_ADDRESS}
      TESTUSER_ID: ${TESTUSER_ID}
      TESTUSER_TRANSLATE_FILENAME: ${TESTUSER_TRANSLATE_FILENAME}
      TESTUSER_ANALYSIS_FILENAME: ${TESTUSER_ANALYSIS_FILENAME}
    # env_file:
    # - ./app/docker/test/.env
    command: flask run --host 0.0.0.0 --port 8000