version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: youtube_analysis_app
    ports:
      - "8000:80"
    volumes:
    - ./app/src:/src
    tty: true
    environment:
      TZ: Asia/Tokyo
    # command: flask run --host 0.0.0.0 --port 8000

  apptest:
    build:
      context: ./apptest
      dockerfile: Dockerfile
    image: youtube_analysis_apptest
    container_name: youtube_analysis_apptest
    depends_on:
      - app
    tty: true
    environment:
      APP_HOST: app
      APP_PORT: 80