name: CI to GCP on loginapi

on:
  push:
    paths:
    - 'loginapi/**'
    branches: [ 'feature/**' ]
env:
  TEST_NAME: loginapi

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_KEYFILE_JSON: ${{ secrets.GCP_KEYFILE_JSON }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDGRID_TEMPLATED_ID: ${{ secrets.SENDGRID_TEMPLATED_ID }}
      SENDGRID_FROM_EMAIL: ${{ secrets.SENDGRID_FROM_EMAIL }}
      CORS_ADDRESS: ${{ secrets.CORS_ADDRESS }}

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: CI/CD
        run: |
          docker-compose -f docker-compose.yml build --no-cache
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml ps
          docker container exec ${{ env.TEST_NAME }} go test -v
          docker-compose -f docker-compose.yml down
        working-directory: ./loginapi
        env:
          TESTUSER_EMAIL: ${{ secrets.TESTUSER_EMAIL }}
          TESTUSER_PASSWORD: ${{ secrets.TESTUSER_PASSWORD }}